Модифіковуємо зображення виділяючи контури


In [2]:
import cv2
import os

# src_dir = './RUSSIAN_PLANES_DB/train'
# src_dir = '../RUSSIAN_PLANAE_DB/test_10/'
# src_dir = '../RUSSIAN_PLANAE_DB/original/'
# dest_dir = '../RUSSIAN_PLANAE_DB/full_modified/'

src_dir =  "C:\\Users\\Северин\\Documents\\unik\\kursova\\DB\\src\\original_src"
dest_dir = "C:\\Users\\Северин\\Documents\\unik\\kursova\\DB\\src\\modified_src"


for filename in os.listdir(src_dir):
    if filename.endswith('.jpg') or filename.endswith('.jpeg') or filename.endswith('.png'):
        img_path = os.path.join(src_dir, filename)
        img = cv2.imread(img_path)
        print(img)
        cv2.imshow('image', img)
        print(os.path.exists(img_path))
        #CANNY
        # edges = cv2.Canny(img,150,250)

        #LAPLACE
        # LESS_CONTRAST_EDGES (ver 1)
        # denoise = cv2.GaussianBlur(img, (3,3), 0)
        # MORE_CONTRAST_EDGES (ver 2)
        denoise = cv2.GaussianBlur(img, (1,1), 0)
        
        #FURTHER_PROCESSING
        to_gray = cv2.cvtColor(denoise,  cv2.COLOR_BGR2GRAY)
        res_lap = cv2.Laplacian(to_gray, cv2.CV_16S, ksize=3)

        cv2.imwrite(os.path.join(dest_dir, filename), res_lap)
        # cv2.imwrite(os.path.join('./test_10_images/', filename), denoise) # last arg denoise or edges
        # cv2.imwrite(os.path.join('./test_10_images/', filename), to_gray)


[[[100 100 118]
  [ 98  98 116]
  [ 94  94 112]
  ...
  [ 75  86  67]
  [ 73  84  64]
  [ 74  85  65]]

 [[ 99  99 117]
  [ 97  97 115]
  [ 95  95 113]
  ...
  [ 71  86  65]
  [ 72  87  64]
  [ 76  91  67]]

 [[ 96  96 114]
  [ 95  95 113]
  [ 95  95 113]
  ...
  [ 72  90  67]
  [ 75  92  68]
  [ 81  98  71]]

 ...

 [[101 110 119]
  [103 112 121]
  [108 115 126]
  ...
  [109 108 102]
  [ 99  97  91]
  [ 94  92  87]]

 [[104 113 124]
  [107 115 127]
  [116 123 137]
  ...
  [109 109 106]
  [ 99 101  95]
  [ 95  96  91]]

 [[109 117 130]
  [116 123 137]
  [123 129 146]
  ...
  [114 115 109]
  [104 106 100]
  [ 96  97  93]]]
True
[[[ 93  95 113]
  [ 92  94 112]
  [ 87  89 107]
  ...
  [ 94  97 104]
  [ 93  96 104]
  [ 92  95 101]]

 [[ 93  95 113]
  [ 90  92 110]
  [ 86  88 106]
  ...
  [ 93  96 103]
  [ 93  96 104]
  [ 93  96 102]]

 [[ 91  93 111]
  [ 89  91 109]
  [ 93  95 113]
  ...
  [ 91  95 101]
  [ 91  94 102]
  [ 92  96 102]]

 ...

 [[130 137 154]
  [143 150 165]
  [154 161 176]

KeyboardInterrupt: 

Для розподілення датасету по train val папках


In [ ]:
import os
import cv2
import shutil


# Шлях до папки з зображеннями
src_folder =   "C:\\Users\\Северин\\Documents\\unik\\kursova\\DB\\src\\modified_src"
train_folder = "C:\\Users\\Северин\\Documents\\unik\\kursova\\DB\\images\\train"
val_folder =   "C:\\Users\\Северин\\Documents\\unik\\kursova\\DB\\images\\val"

# Отримати список всіх файлів у початковій папці
all_files = [f for f in os.listdir(src_folder) if os.path.isfile(os.path.join(src_folder, f))]

# Відсортувати файли (опціонально, залежить від вимог)
all_files.sort()

# Останні 50 файлів для валідаційного набору
val_files = all_files[-50:]
# Решта файлів для тренувального набору
train_files = all_files[:-50]

# Створити папки train та val, якщо вони ще не існують
os.makedirs(train_folder, exist_ok=True)
os.makedirs(val_folder, exist_ok=True)

# Переміщення файлів
for file_name in train_files:
    shutil.move(os.path.join(src_folder, file_name), os.path.join(train_folder, file_name))

for file_name in val_files:
    shutil.move(os.path.join(src_folder, file_name), os.path.join(val_folder, file_name))

print("Файли успішно розподілені між train та val папками.")


Тренування моделі

In [1]:
# TRAINING & TEST MODEL
import torch
from ultralytics import YOLO
import os

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'avialable device: {device}')
torch.backends.cudnn.enabled = False

# Load a model
# project_folder = "C:\\Users\\Северин\\Documents\\unik\\kursova"
# model = YOLO('yolov8n.yaml')
# data = project_folder + 'src/CustomPlane_copy.yaml'

# load model
data = "CustomPlane.yaml"
model = YOLO('yolov8n.yaml')
model = YOLO('pts\\yolov8n.pt')

# Train and use the model with 527 images
results = model.train(data=data, epochs=200, imgsz=720, augment=True, device=0)
results = model.val()
results = model('..\\DB\\images\\train\\0266.png')

avialable device: cuda
New https://pypi.org/project/ultralytics/8.2.19 available  Update with 'pip install -U ultralytics'
Ultralytics YOLOv8.2.18  Python-3.12.3 torch-2.3.0+cu121 CUDA:0 (NVIDIA GeForce GTX 1650, 4096MiB)
engine\trainer: task=detect, mode=train, model=pts\yolov8n.pt, data=CustomPlane.yaml, epochs=200, time=None, patience=100, batch=16, imgsz=720, save=True, save_period=-1, cache=False, device=0, workers=8, project=None, name=train2, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=True, agnostic_nms=False, classes=None, retina_masks=False, embed

train: Scanning C:\Users\Северин\Documents\unik\kursova\DB\labels\train.cache... 469 images, 2 backgrounds, 0 corrupt: 100%|██████████| 471/471 [00:00<?, ?it/s]
val: Scanning C:\Users\Северин\Documents\unik\kursova\DB\labels\val.cache... 50 images, 0 backgrounds, 0 corrupt: 100%|██████████| 50/50 [00:00<?, ?it/s]


Plotting labels to c:\Users\\Documents\unik\kursova\runs\detect\train2\labels.jpg... 
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: AdamW(lr=0.00037, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 736 train, 736 val
Using 8 dataloader workers
Logging results to c:\Users\\Documents\unik\kursova\runs\detect\train2
Starting training for 200 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      1/200      5.47G      3.038      5.548      1.414        183        736: 100%|██████████| 30/30 [01:06<00:00,  2.22s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.04it/s]

                   all         50        756          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      2/200      5.35G      2.494      4.702      1.104        138        736: 100%|██████████| 30/30 [01:06<00:00,  2.21s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.05it/s]

                   all         50        756     0.0474      0.174     0.0482     0.0208



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      3/200       4.4G      2.398      4.119      1.058        156        736: 100%|██████████| 30/30 [01:06<00:00,  2.21s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756     0.0281      0.302     0.0575     0.0247



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      4/200      4.46G      2.308      3.671      1.036        228        736: 100%|██████████| 30/30 [01:03<00:00,  2.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756       0.38      0.104     0.0645     0.0294



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      5/200      3.83G      2.277      3.479      1.027        170        736: 100%|██████████| 30/30 [01:03<00:00,  2.11s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.07it/s]

                   all         50        756      0.344      0.165     0.0783     0.0356



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      6/200      4.11G      2.207       3.28      1.032        328        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.08it/s]

                   all         50        756       0.22      0.212     0.0896      0.042



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      7/200      4.22G      2.182      3.134      1.021        102        736: 100%|██████████| 30/30 [01:03<00:00,  2.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.08it/s]

                   all         50        756       0.24      0.254      0.108     0.0532



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      8/200      4.84G      2.084      2.908       1.01        175        736: 100%|██████████| 30/30 [01:04<00:00,  2.15s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.05it/s]

                   all         50        756      0.221      0.288      0.106     0.0519



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      9/200      5.14G      2.112      2.867      1.024        170        736: 100%|██████████| 30/30 [01:05<00:00,  2.17s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.08it/s]

                   all         50        756      0.324      0.169      0.114     0.0541



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     10/200      4.75G      2.062      2.754      1.004        135        736: 100%|██████████| 30/30 [01:14<00:00,  2.50s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:02<00:00,  1.18s/it]

                   all         50        756      0.184      0.232      0.109     0.0564



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     11/200      5.25G      2.036      2.719     0.9967        156        736: 100%|██████████| 30/30 [01:05<00:00,  2.18s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.175       0.17      0.106     0.0543



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     12/200      4.91G       2.01      2.638      1.005        216        736: 100%|██████████| 30/30 [01:05<00:00,  2.18s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.00it/s]

                   all         50        756      0.163      0.239      0.116     0.0604



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     13/200      4.52G      2.019      2.587          1        244        736: 100%|██████████| 30/30 [01:04<00:00,  2.15s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.07it/s]

                   all         50        756      0.406      0.179      0.117     0.0607



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     14/200       3.9G      2.017      2.551     0.9862         94        736: 100%|██████████| 30/30 [01:03<00:00,  2.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.06it/s]

                   all         50        756      0.196      0.213      0.145     0.0779



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     15/200      4.53G       2.01      2.525     0.9943        380        736: 100%|██████████| 30/30 [01:05<00:00,  2.18s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.00it/s]

                   all         50        756        0.2       0.16      0.143     0.0786



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     16/200      5.24G      1.971      2.412     0.9888        148        736: 100%|██████████| 30/30 [01:17<00:00,  2.59s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:02<00:00,  1.24s/it]

                   all         50        756      0.212      0.206      0.154     0.0816



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     17/200      4.54G      1.958       2.42     0.9819        188        736: 100%|██████████| 30/30 [01:09<00:00,  2.31s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.03it/s]

                   all         50        756      0.205      0.233      0.157     0.0797



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     18/200      4.26G      1.953      2.343     0.9758        178        736: 100%|██████████| 30/30 [01:07<00:00,  2.24s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.237      0.194      0.144     0.0762



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     19/200      4.01G      1.963      2.322      0.981        217        736: 100%|██████████| 30/30 [01:03<00:00,  2.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.08it/s]

                   all         50        756      0.132      0.209      0.149     0.0773



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     20/200      4.41G      1.942      2.262     0.9777        289        736: 100%|██████████| 30/30 [01:04<00:00,  2.16s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.08it/s]

                   all         50        756      0.183      0.216      0.152     0.0843



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     21/200      3.96G      1.881      2.196     0.9712        146        736: 100%|██████████| 30/30 [01:03<00:00,  2.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.08it/s]

                   all         50        756      0.206      0.269      0.162     0.0901



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     22/200      4.57G      1.894      2.152     0.9729        157        736: 100%|██████████| 30/30 [01:07<00:00,  2.25s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:02<00:00,  1.12s/it]

                   all         50        756      0.227      0.226      0.152     0.0791



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     23/200      5.41G      1.904      2.143     0.9771        200        736: 100%|██████████| 30/30 [01:07<00:00,  2.25s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.01it/s]

                   all         50        756       0.17      0.214      0.181     0.0915



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     24/200      5.05G       1.89      2.156     0.9761        159        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.08it/s]

                   all         50        756      0.211       0.27      0.174     0.0936



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     25/200      4.08G      1.883      2.029       0.97        248        736: 100%|██████████| 30/30 [01:03<00:00,  2.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.08it/s]

                   all         50        756      0.153      0.299      0.196      0.108



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     26/200      4.63G      1.842       1.96     0.9684        228        736: 100%|██████████| 30/30 [01:04<00:00,  2.16s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.05it/s]

                   all         50        756      0.161      0.236      0.177      0.094



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     27/200       5.3G      1.894      2.057     0.9724        368        736: 100%|██████████| 30/30 [01:05<00:00,  2.17s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.172      0.248      0.175     0.0959



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     28/200      4.33G      1.885       1.97     0.9718        153        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.07it/s]

                   all         50        756        0.2      0.281      0.196      0.102



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     29/200      3.72G      1.802      1.909     0.9581        150        736: 100%|██████████| 30/30 [01:03<00:00,  2.11s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.08it/s]

                   all         50        756      0.187      0.219      0.166     0.0888



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     30/200      4.88G      1.801      1.883     0.9607        137        736: 100%|██████████| 30/30 [01:05<00:00,  2.18s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.00it/s]

                   all         50        756      0.172      0.298      0.193      0.104



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     31/200      3.87G      1.854      1.919      0.965        365        736: 100%|██████████| 30/30 [01:03<00:00,  2.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.08it/s]

                   all         50        756      0.202      0.275      0.218      0.115



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     32/200      5.47G      1.787       1.82     0.9592        122        736: 100%|██████████| 30/30 [01:05<00:00,  2.17s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.08it/s]

                   all         50        756      0.208      0.246      0.194       0.11



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     33/200      4.44G      1.836      1.875     0.9643        264        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.04it/s]

                   all         50        756       0.21      0.232      0.173     0.0976



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     34/200      4.25G      1.825       1.79     0.9551        167        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.07it/s]

                   all         50        756      0.197       0.22      0.188      0.104



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     35/200      4.85G      1.796       1.75     0.9575        275        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.07it/s]

                   all         50        756      0.256      0.247      0.191      0.102



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     36/200      4.43G      1.786      1.735     0.9555        114        736: 100%|██████████| 30/30 [01:03<00:00,  2.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.283      0.239      0.204       0.11



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     37/200      4.53G      1.789      1.707     0.9501        195        736: 100%|██████████| 30/30 [01:09<00:00,  2.31s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:02<00:00,  1.12s/it]

                   all         50        756      0.169      0.231      0.178     0.0981



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     38/200      5.47G      1.806      1.716     0.9523        141        736: 100%|██████████| 30/30 [01:04<00:00,  2.17s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.193      0.272      0.193      0.107



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     39/200      4.47G      1.851      1.739      0.953        200        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.08it/s]

                   all         50        756      0.162      0.306       0.19      0.101



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     40/200      4.05G       1.79      1.675     0.9535        212        736: 100%|██████████| 30/30 [01:04<00:00,  2.16s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.07it/s]

                   all         50        756      0.396      0.196      0.206       0.11



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     41/200       4.3G      1.782      1.651     0.9507        320        736: 100%|██████████| 30/30 [01:03<00:00,  2.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.259      0.254      0.183      0.097



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     42/200      4.56G      1.767       1.62     0.9498         95        736: 100%|██████████| 30/30 [01:03<00:00,  2.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.169      0.242      0.157     0.0883



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     43/200      4.53G       1.76      1.615     0.9504        176        736: 100%|██████████| 30/30 [01:03<00:00,  2.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.166      0.281      0.176      0.103



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     44/200      3.96G      1.827      1.652     0.9538        127        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.08it/s]

                   all         50        756      0.234      0.298      0.255      0.163



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     45/200      4.45G       1.78       1.57      0.943        153        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.08it/s]

                   all         50        756      0.213      0.238      0.208      0.121



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     46/200      4.41G      1.751      1.535     0.9454         90        736: 100%|██████████| 30/30 [01:04<00:00,  2.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.314      0.234      0.213      0.115



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     47/200      4.49G      1.726      1.536     0.9497        154        736: 100%|██████████| 30/30 [01:05<00:00,  2.17s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.05it/s]

                   all         50        756      0.255      0.191      0.179      0.102



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     48/200      4.13G      1.747      1.489     0.9454        221        736: 100%|██████████| 30/30 [01:03<00:00,  2.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.247      0.229      0.184      0.105



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     49/200      4.56G      1.712      1.488     0.9443        196        736: 100%|██████████| 30/30 [01:04<00:00,  2.16s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.256       0.28      0.235      0.131



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     50/200      4.77G      1.712      1.479     0.9351        143        736: 100%|██████████| 30/30 [01:04<00:00,  2.16s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.07it/s]

                   all         50        756      0.255      0.252      0.227      0.128



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     51/200      4.18G      1.716      1.473     0.9419        157        736: 100%|██████████| 30/30 [01:03<00:00,  2.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.217      0.248      0.205      0.116



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     52/200      4.21G      1.732      1.467     0.9479        154        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.339      0.207      0.213      0.118



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     53/200      4.77G      1.726      1.436     0.9455        140        736: 100%|██████████| 30/30 [01:04<00:00,  2.16s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.08it/s]

                   all         50        756      0.234      0.274      0.214      0.119



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     54/200      4.49G      1.739      1.438     0.9344        200        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.351      0.187      0.208      0.119



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     55/200      4.44G      1.713      1.443     0.9364        199        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.207       0.24      0.192      0.108



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     56/200      4.66G      1.729      1.449     0.9466        276        736: 100%|██████████| 30/30 [01:04<00:00,  2.15s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.169      0.279      0.208      0.118



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     57/200      4.16G      1.687       1.37     0.9336        216        736: 100%|██████████| 30/30 [01:09<00:00,  2.32s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:02<00:00,  1.12s/it]

                   all         50        756      0.223      0.255      0.248       0.14



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     58/200      4.46G      1.699      1.399     0.9337        191        736: 100%|██████████| 30/30 [01:05<00:00,  2.17s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.06it/s]

                   all         50        756      0.147       0.28      0.176      0.104



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     59/200      4.62G      1.693      1.392     0.9349        267        736: 100%|██████████| 30/30 [01:05<00:00,  2.17s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.01it/s]

                   all         50        756        0.2      0.234      0.212      0.116



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     60/200      4.33G      1.677      1.395     0.9324        145        736: 100%|██████████| 30/30 [01:10<00:00,  2.36s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:02<00:00,  1.12s/it]

                   all         50        756      0.231      0.239      0.223      0.126



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     61/200      3.85G      1.698       1.37     0.9306        224        736: 100%|██████████| 30/30 [01:03<00:00,  2.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.213      0.264      0.222      0.128



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     62/200      4.45G      1.678      1.321      0.933        150        736: 100%|██████████| 30/30 [01:03<00:00,  2.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.364      0.255      0.202      0.113



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     63/200      4.15G      1.653      1.342     0.9368         78        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.287      0.253       0.22      0.123



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     64/200      3.85G      1.722      1.361     0.9291        239        736: 100%|██████████| 30/30 [01:03<00:00,  2.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.251      0.251      0.183      0.106



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     65/200      3.72G      1.652      1.301     0.9261        172        736: 100%|██████████| 30/30 [01:03<00:00,  2.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.254      0.259      0.263       0.16



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     66/200      3.72G      1.646      1.288     0.9213        263        736: 100%|██████████| 30/30 [01:03<00:00,  2.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.291      0.287      0.226      0.131



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     67/200      4.54G      1.658       1.28     0.9302        199        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.229      0.258      0.202      0.113



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     68/200       4.4G       1.66      1.275     0.9278        209        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.226      0.288      0.244      0.133



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     69/200      4.69G      1.622      1.253     0.9299        133        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756       0.21      0.291      0.214      0.122



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     70/200      5.04G      1.672       1.26      0.924        166        736: 100%|██████████| 30/30 [01:04<00:00,  2.15s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.01it/s]

                   all         50        756      0.311      0.217      0.221      0.126



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     71/200      3.91G      1.636      1.233     0.9202        221        736: 100%|██████████| 30/30 [01:03<00:00,  2.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.206      0.284      0.228      0.134



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     72/200      4.18G      1.655      1.259     0.9177        207        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.213      0.307      0.229      0.136



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     73/200      4.27G      1.608      1.213     0.9234        331        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.06it/s]

                   all         50        756      0.176      0.295      0.188      0.105



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     74/200      4.58G       1.67      1.289     0.9266        381        736: 100%|██████████| 30/30 [01:05<00:00,  2.18s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.187      0.288      0.194       0.11



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     75/200      5.19G      1.635      1.222     0.9222        165        736: 100%|██████████| 30/30 [01:04<00:00,  2.16s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.08it/s]

                   all         50        756      0.188       0.25      0.224       0.13



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     76/200      5.19G      1.631      1.189     0.9271        304        736: 100%|██████████| 30/30 [01:04<00:00,  2.16s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.234      0.311      0.256      0.167



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     77/200      3.79G      1.571      1.131     0.9245        127        736: 100%|██████████| 30/30 [01:03<00:00,  2.11s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.233      0.353      0.259      0.159



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     78/200      5.43G      1.623      1.193     0.9189        304        736: 100%|██████████| 30/30 [01:05<00:00,  2.18s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.344      0.241      0.217       0.13



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     79/200      5.02G       1.59      1.171      0.918        126        736: 100%|██████████| 30/30 [01:04<00:00,  2.16s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.242      0.292      0.239       0.14



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     80/200      4.39G      1.631      1.183     0.9154        191        736: 100%|██████████| 30/30 [01:03<00:00,  2.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.223      0.285      0.208      0.117



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     81/200      4.49G      1.619      1.191     0.9208        226        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.231      0.317      0.227      0.128



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     82/200      4.26G      1.656      1.182     0.9234        151        736: 100%|██████████| 30/30 [01:03<00:00,  2.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.291      0.279      0.279      0.158



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     83/200      4.16G      1.608      1.153     0.9245        218        736: 100%|██████████| 30/30 [01:03<00:00,  2.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.219      0.257      0.242      0.139



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     84/200       4.8G      1.651      1.163     0.9221        183        736: 100%|██████████| 30/30 [01:04<00:00,  2.16s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.03it/s]

                   all         50        756       0.23      0.281      0.221      0.129



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     85/200      4.65G      1.573      1.124     0.9252        205        736: 100%|██████████| 30/30 [01:04<00:00,  2.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.191      0.263      0.211      0.119



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     86/200      4.21G      1.611      1.153     0.9183        160        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.01it/s]

                   all         50        756      0.214      0.309      0.266      0.157



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     87/200      4.46G       1.59      1.122     0.9145        221        736: 100%|██████████| 30/30 [01:04<00:00,  2.17s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:02<00:00,  1.16s/it]

                   all         50        756      0.174      0.255      0.187      0.111



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     88/200       4.4G        1.6       1.15     0.9066        415        736: 100%|██████████| 30/30 [01:04<00:00,  2.15s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.173       0.33      0.204      0.119



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     89/200      3.88G      1.598      1.141     0.9084        294        736: 100%|██████████| 30/30 [01:03<00:00,  2.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.293      0.246      0.182      0.104



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     90/200      4.99G      1.588      1.124      0.911        228        736: 100%|██████████| 30/30 [01:16<00:00,  2.57s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:02<00:00,  1.20s/it]

                   all         50        756      0.268      0.257        0.2      0.111



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     91/200      3.62G      1.605      1.131     0.9141        235        736: 100%|██████████| 30/30 [01:03<00:00,  2.11s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.198      0.207      0.186      0.106



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     92/200      4.34G       1.58      1.128      0.915        179        736: 100%|██████████| 30/30 [01:05<00:00,  2.17s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.02it/s]

                   all         50        756      0.222      0.216      0.202      0.116



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     93/200      4.41G      1.573      1.106     0.9082        174        736: 100%|██████████| 30/30 [01:04<00:00,  2.15s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.284      0.231      0.219      0.124



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     94/200      4.48G      1.595      1.142     0.9055        212        736: 100%|██████████| 30/30 [01:03<00:00,  2.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.08it/s]

                   all         50        756      0.227      0.247      0.222      0.128



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     95/200      4.77G      1.596      1.095     0.9088        217        736: 100%|██████████| 30/30 [01:04<00:00,  2.16s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.239      0.256      0.223      0.128



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     96/200      4.14G      1.553      1.081      0.908        174        736: 100%|██████████| 30/30 [01:03<00:00,  2.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.182      0.279      0.191      0.109



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     97/200       4.4G      1.585      1.103     0.9111        236        736: 100%|██████████| 30/30 [01:03<00:00,  2.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.185       0.31      0.194      0.105



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     98/200      4.34G      1.561      1.077     0.9097        190        736: 100%|██████████| 30/30 [01:05<00:00,  2.18s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.02it/s]

                   all         50        756      0.179      0.283      0.196      0.106



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


     99/200      4.45G       1.56      1.065     0.9034        377        736: 100%|██████████| 30/30 [01:04<00:00,  2.15s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.214      0.237      0.207      0.112



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    100/200      4.67G      1.572      1.093     0.9049        229        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.194      0.266       0.21      0.116



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    101/200       4.3G      1.558      1.056     0.9118        199        736: 100%|██████████| 30/30 [01:03<00:00,  2.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.295      0.183      0.209      0.119



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    102/200       5.1G      1.566      1.043     0.9058        251        736: 100%|██████████| 30/30 [01:05<00:00,  2.17s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.253      0.256      0.243      0.141



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    103/200      3.88G      1.547      1.065     0.9026        236        736: 100%|██████████| 30/30 [01:03<00:00,  2.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.227      0.298      0.269       0.17



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    104/200      4.46G      1.516      1.046     0.9076        129        736: 100%|██████████| 30/30 [01:04<00:00,  2.15s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.02it/s]

                   all         50        756      0.316      0.269      0.282      0.167



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    105/200      5.08G      1.536      1.042     0.9014        129        736: 100%|██████████| 30/30 [01:04<00:00,  2.16s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.08it/s]

                   all         50        756      0.233      0.308      0.228      0.133



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    106/200      4.24G      1.542      1.061     0.9098        197        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.236      0.326      0.241      0.141



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    107/200      4.37G      1.536      1.046     0.9026        131        736: 100%|██████████| 30/30 [01:04<00:00,  2.15s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.226       0.26      0.219      0.123



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    108/200      5.26G      1.527       1.05     0.9012        153        736: 100%|██████████| 30/30 [01:04<00:00,  2.16s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.196      0.222      0.202      0.117



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    109/200      4.28G      1.527       1.02     0.8998        178        736: 100%|██████████| 30/30 [01:03<00:00,  2.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.265      0.305      0.232      0.133



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    110/200      3.96G      1.526      1.006     0.9037        236        736: 100%|██████████| 30/30 [01:03<00:00,  2.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.228      0.243      0.215      0.122



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    111/200      4.57G      1.537      1.022     0.9009        127        736: 100%|██████████| 30/30 [01:03<00:00,  2.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.244      0.287      0.226      0.135



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    112/200      4.99G      1.508      1.031      0.901         86        736: 100%|██████████| 30/30 [01:05<00:00,  2.17s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.329      0.234      0.244      0.138



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    113/200      4.49G      1.506      1.018     0.8955        256        736: 100%|██████████| 30/30 [01:04<00:00,  2.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.05it/s]

                   all         50        756      0.254      0.257      0.265      0.166



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    114/200      4.36G      1.529          1     0.8966        208        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.06it/s]

                   all         50        756      0.172      0.248      0.206      0.119



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    115/200      4.74G      1.531      1.014     0.8992        207        736: 100%|██████████| 30/30 [01:04<00:00,  2.15s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.224      0.267      0.268      0.171



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    116/200      4.44G      1.497     0.9871     0.8998        236        736: 100%|██████████| 30/30 [01:03<00:00,  2.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.267      0.183      0.208      0.122



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    117/200      4.44G       1.52      1.008     0.9011        197        736: 100%|██████████| 30/30 [01:05<00:00,  2.17s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.273      0.207      0.227      0.132



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    118/200      4.65G      1.534      1.025     0.8952        242        736: 100%|██████████| 30/30 [01:05<00:00,  2.17s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.195       0.27      0.232      0.132



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    119/200      4.82G      1.511      1.016     0.8992        122        736: 100%|██████████| 30/30 [01:04<00:00,  2.16s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.01it/s]

                   all         50        756      0.211      0.337      0.226      0.126



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    120/200      4.26G      1.519      1.012     0.8958        122        736: 100%|██████████| 30/30 [01:03<00:00,  2.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.193      0.307      0.222      0.125



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    121/200       4.5G      1.487     0.9763     0.8949        165        736: 100%|██████████| 30/30 [01:04<00:00,  2.16s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.227      0.256      0.214       0.12



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    122/200      4.08G      1.521     0.9927     0.8977        133        736: 100%|██████████| 30/30 [01:03<00:00,  2.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.248       0.34      0.287      0.159



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    123/200      4.27G      1.493     0.9726     0.8949        212        736: 100%|██████████| 30/30 [01:03<00:00,  2.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.08it/s]

                   all         50        756      0.217      0.325      0.272      0.153



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    124/200      5.61G      1.471     0.9757     0.8993        294        736: 100%|██████████| 30/30 [01:05<00:00,  2.19s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.01it/s]

                   all         50        756      0.256      0.266      0.222      0.122



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    125/200      4.43G      1.493     0.9755     0.8914        215        736: 100%|██████████| 30/30 [01:05<00:00,  2.19s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:02<00:00,  1.05s/it]

                   all         50        756      0.188      0.314      0.256      0.147



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    126/200      4.39G      1.494     0.9735     0.8967        194        736: 100%|██████████| 30/30 [01:03<00:00,  2.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.163      0.246      0.204      0.116



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    127/200      4.62G      1.492     0.9947     0.8912        246        736: 100%|██████████| 30/30 [01:04<00:00,  2.16s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.191      0.232      0.222      0.126



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    128/200      4.61G      1.495      0.963     0.8946        219        736: 100%|██████████| 30/30 [01:08<00:00,  2.30s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:02<00:00,  1.08s/it]

                   all         50        756      0.197      0.251      0.222      0.123



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    129/200         5G      1.462     0.9399     0.8901        145        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.279      0.235      0.226      0.122



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    130/200      5.23G      1.485     0.9422     0.8893        157        736: 100%|██████████| 30/30 [01:05<00:00,  2.17s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.199      0.263      0.213      0.119



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    131/200      4.53G      1.457     0.9407     0.8928        222        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.235      0.317      0.239      0.135



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    132/200      4.58G      1.481     0.9493     0.8931        248        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.176      0.244      0.208      0.113



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    133/200      4.62G      1.462     0.9538     0.8938        256        736: 100%|██████████| 30/30 [01:04<00:00,  2.16s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.03it/s]

                   all         50        756      0.277      0.245      0.225      0.123



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    134/200      5.42G      1.496      0.958     0.8888        216        736: 100%|██████████| 30/30 [01:04<00:00,  2.16s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.261      0.217      0.214      0.121



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    135/200       4.6G       1.48     0.9544     0.8897        167        736: 100%|██████████| 30/30 [01:03<00:00,  2.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.237      0.254      0.197      0.108



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    136/200      3.84G      1.478     0.9463     0.8881        161        736: 100%|██████████| 30/30 [01:03<00:00,  2.11s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.234      0.234      0.191      0.108



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    137/200      3.94G      1.418     0.9083      0.889        303        736: 100%|██████████| 30/30 [01:03<00:00,  2.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.256      0.204      0.197      0.111



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    138/200      4.77G      1.452     0.9253     0.8829        168        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.193       0.28      0.201       0.11



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    139/200       4.6G      1.455     0.9519     0.8907        260        736: 100%|██████████| 30/30 [01:04<00:00,  2.15s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756       0.19      0.235      0.207      0.119



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    140/200      4.29G      1.474     0.9511     0.8909        364        736: 100%|██████████| 30/30 [01:03<00:00,  2.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.243      0.315      0.264      0.149



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    141/200      5.25G      1.455     0.9319     0.8927        202        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756       0.21      0.347      0.272      0.157



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    142/200      3.88G      1.445     0.9238     0.8875        204        736: 100%|██████████| 30/30 [01:03<00:00,  2.11s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.229      0.298      0.238      0.137



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    143/200      3.85G      1.481     0.9386     0.8865        223        736: 100%|██████████| 30/30 [01:03<00:00,  2.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.184      0.248      0.208      0.118



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    144/200      4.35G      1.456     0.9219     0.8845        237        736: 100%|██████████| 30/30 [01:04<00:00,  2.15s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.277      0.253      0.213      0.119



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    145/200      4.61G      1.462     0.9227      0.884        135        736: 100%|██████████| 30/30 [01:04<00:00,  2.15s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.277      0.236       0.21      0.119



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    146/200      4.17G      1.435     0.9232     0.8859         73        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.258      0.226      0.249      0.149



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    147/200      4.44G      1.423      0.899     0.8842        229        736: 100%|██████████| 30/30 [01:03<00:00,  2.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.293      0.201      0.206      0.115



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    148/200       4.5G      1.435     0.9199     0.8901        232        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.06it/s]

                   all         50        756      0.272      0.229      0.203      0.114



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    149/200      4.18G      1.454     0.9226     0.8869        164        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.185      0.262      0.212      0.121



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    150/200      4.48G      1.433     0.9165     0.8853        135        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.08it/s]

                   all         50        756      0.195      0.245      0.198      0.111



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    151/200      4.75G       1.42      0.898      0.888        245        736: 100%|██████████| 30/30 [01:12<00:00,  2.42s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:02<00:00,  1.09s/it]

                   all         50        756      0.269      0.238      0.212      0.119



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    152/200      4.45G      1.443      0.906     0.8883        272        736: 100%|██████████| 30/30 [01:03<00:00,  2.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.08it/s]

                   all         50        756      0.272      0.247      0.208      0.117



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    153/200      4.32G      1.443     0.9114     0.8844        152        736: 100%|██████████| 30/30 [01:03<00:00,  2.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.332      0.185      0.207      0.116



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    154/200      4.52G      1.428      0.891     0.8839        155        736: 100%|██████████| 30/30 [01:05<00:00,  2.17s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:02<00:00,  1.16s/it]

                   all         50        756      0.184      0.274      0.213      0.121



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    155/200      4.57G      1.433     0.8947     0.8845        210        736: 100%|██████████| 30/30 [01:04<00:00,  2.15s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.295      0.228      0.212      0.118



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    156/200      4.56G      1.437     0.9064     0.8822        186        736: 100%|██████████| 30/30 [01:04<00:00,  2.16s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.303      0.211      0.216      0.122



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    157/200      5.18G      1.434     0.8913     0.8871        187        736: 100%|██████████| 30/30 [01:06<00:00,  2.22s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:02<00:00,  1.25s/it]

                   all         50        756      0.235      0.305      0.263      0.158



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    158/200      4.17G      1.452     0.9251     0.8859        397        736: 100%|██████████| 30/30 [01:03<00:00,  2.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.264      0.242      0.226      0.133



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    159/200      4.48G      1.428     0.8951     0.8802        180        736: 100%|██████████| 30/30 [01:03<00:00,  2.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.251      0.244       0.25      0.149



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    160/200      4.61G      1.442     0.8971     0.8865        316        736: 100%|██████████| 30/30 [01:04<00:00,  2.15s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.228       0.32      0.261      0.154



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    161/200      5.36G      1.415     0.8892     0.8767        209        736: 100%|██████████| 30/30 [01:04<00:00,  2.15s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756        0.2      0.325       0.21      0.119



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    162/200      3.89G      1.429     0.8955     0.8794        140        736: 100%|██████████| 30/30 [01:04<00:00,  2.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.218       0.27      0.223      0.127



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    163/200      3.75G      1.427     0.9098     0.8851        157        736: 100%|██████████| 30/30 [01:03<00:00,  2.11s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.258      0.226       0.23      0.131



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    164/200      4.18G      1.397     0.8978     0.8816        305        736: 100%|██████████| 30/30 [01:03<00:00,  2.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.274      0.219      0.201      0.115



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    165/200      4.19G      1.455      0.908     0.8823        211        736: 100%|██████████| 30/30 [01:03<00:00,  2.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.263      0.231      0.201       0.11



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    166/200      4.06G        1.4     0.8716     0.8799        201        736: 100%|██████████| 30/30 [01:03<00:00,  2.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.248      0.236      0.199      0.112



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    167/200      4.25G      1.399      0.866     0.8872        128        736: 100%|██████████| 30/30 [01:03<00:00,  2.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.216      0.329       0.22      0.124



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    168/200      4.28G      1.409     0.8932     0.8839        104        736: 100%|██████████| 30/30 [01:03<00:00,  2.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.197      0.264       0.22      0.122



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    169/200      4.68G      1.415     0.8792     0.8834        214        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.254      0.242      0.235      0.135



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    170/200      4.71G      1.427     0.8828     0.8769        301        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.251      0.269      0.234      0.134



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    171/200      4.49G      1.409     0.8714      0.881        165        736: 100%|██████████| 30/30 [01:03<00:00,  2.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.253      0.234      0.202      0.114



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    172/200      3.72G      1.383     0.8572     0.8797        131        736: 100%|██████████| 30/30 [01:03<00:00,  2.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.302      0.215      0.216      0.118



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    173/200      4.36G      1.398     0.8751     0.8812        198        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.312      0.216      0.216      0.121



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    174/200      4.23G      1.378     0.8561     0.8803        238        736: 100%|██████████| 30/30 [01:03<00:00,  2.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.276      0.235       0.21      0.117



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    175/200      4.57G      1.401     0.8713     0.8792        150        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.307      0.214      0.204      0.111



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    176/200      4.58G       1.38     0.8598      0.875        200        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.267      0.263      0.217       0.12



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    177/200      4.14G      1.402     0.8599     0.8808        239        736: 100%|██████████| 30/30 [01:03<00:00,  2.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.265      0.268      0.224      0.126



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    178/200      4.63G       1.39     0.8565     0.8762        166        736: 100%|██████████| 30/30 [01:04<00:00,  2.15s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.03it/s]

                   all         50        756      0.322      0.235      0.215      0.118



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    179/200      4.79G      1.416     0.8774     0.8802        178        736: 100%|██████████| 30/30 [01:04<00:00,  2.15s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.274       0.25      0.212      0.118



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    180/200      4.78G      1.391     0.8649     0.8777        275        736: 100%|██████████| 30/30 [01:04<00:00,  2.16s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756       0.29      0.205      0.198       0.11



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    181/200      4.57G      1.401     0.8699      0.873        248        736: 100%|██████████| 30/30 [01:03<00:00,  2.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.257      0.225      0.203      0.112



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    182/200      4.16G      1.418     0.8761     0.8755        209        736: 100%|██████████| 30/30 [01:04<00:00,  2.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.308      0.216       0.21      0.116



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    183/200      3.71G      1.379     0.8629     0.8825        189        736: 100%|██████████| 30/30 [01:03<00:00,  2.11s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.272      0.246       0.21      0.115



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    184/200      4.68G      1.393     0.8531     0.8759        309        736: 100%|██████████| 30/30 [01:04<00:00,  2.16s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.271      0.253       0.21      0.114



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    185/200      4.51G      1.388     0.8457     0.8745        227        736: 100%|██████████| 30/30 [01:03<00:00,  2.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.258      0.234      0.205      0.114



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    186/200      3.92G      1.403     0.8578     0.8731        209        736: 100%|██████████| 30/30 [01:03<00:00,  2.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.262      0.241      0.207      0.115



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    187/200      4.88G      1.405      0.862     0.8765        109        736: 100%|██████████| 30/30 [01:05<00:00,  2.17s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756       0.28      0.272      0.207      0.114



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    188/200      4.48G      1.379      0.844     0.8752        250        736: 100%|██████████| 30/30 [01:03<00:00,  2.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756       0.28       0.27      0.207      0.114



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    189/200      4.09G      1.386     0.8568     0.8761        237        736: 100%|██████████| 30/30 [01:03<00:00,  2.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.277       0.26      0.213      0.118



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    190/200       4.9G      1.375     0.8545     0.8757        178        736: 100%|██████████| 30/30 [01:04<00:00,  2.16s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:02<00:00,  1.06s/it]

                   all         50        756      0.281      0.262      0.217       0.12


Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    191/200      4.22G      1.449     0.9323     0.8974        124        736: 100%|██████████| 30/30 [01:03<00:00,  2.11s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756       0.27      0.252      0.216      0.121



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    192/200      3.91G      1.448     0.9356     0.8942         75        736: 100%|██████████| 30/30 [01:03<00:00,  2.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.195       0.27      0.217      0.121



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    193/200      3.93G      1.388     0.8499     0.8801         70        736: 100%|██████████| 30/30 [01:03<00:00,  2.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.10it/s]

                   all         50        756      0.212      0.287      0.212      0.118



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    194/200      3.78G      1.416      0.868     0.8853        135        736: 100%|██████████| 30/30 [01:02<00:00,  2.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756       0.21      0.288       0.21      0.115



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    195/200      4.37G      1.373     0.8291     0.8838        220        736: 100%|██████████| 30/30 [01:03<00:00,  2.11s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.08it/s]

                   all         50        756      0.204      0.289      0.208      0.114



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    196/200      4.28G      1.361     0.8189     0.8795         95        736: 100%|██████████| 30/30 [01:03<00:00,  2.11s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.204      0.277      0.205      0.113



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    197/200      4.51G       1.37     0.8274     0.8853        114        736: 100%|██████████| 30/30 [01:03<00:00,  2.11s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.202      0.286      0.208      0.114



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    198/200      4.28G      1.345     0.8122     0.8814         98        736: 100%|██████████| 30/30 [01:03<00:00,  2.11s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.207      0.302      0.209      0.116



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    199/200      3.97G      1.337     0.8059     0.8818         80        736: 100%|██████████| 30/30 [01:03<00:00,  2.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.09it/s]

                   all         50        756      0.216        0.3      0.206      0.114



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


    200/200      4.19G      1.346     0.8121     0.8819         98        736: 100%|██████████| 30/30 [01:03<00:00,  2.11s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:01<00:00,  1.04it/s]

                   all         50        756      0.212      0.293      0.208      0.115



200 epochs completed in 3.721 hours.
Optimizer stripped from c:\Users\\Documents\unik\kursova\runs\detect\train2\weights\last.pt, 6.3MB
Optimizer stripped from c:\Users\\Documents\unik\kursova\runs\detect\train2\weights\best.pt, 6.3MB

Validating c:\Users\\Documents\unik\kursova\runs\detect\train2\weights\best.pt...
Ultralytics YOLOv8.2.18  Python-3.12.3 torch-2.3.0+cu121 CUDA:0 (NVIDIA GeForce GTX 1650, 4096MiB)
Model summary (fused): 168 layers, 3010133 parameters, 0 gradients


                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:04<00:00,  2.09s/it]


                   all         50        756      0.254      0.197      0.221      0.126
            Helicopter         50         44     0.0935     0.0227     0.0632     0.0224
USSR|CIV/Transport|AN-124         50         33      0.475      0.247      0.335      0.201
USSR|CIV/Transport/Recon.|AN-24/26/30         50         21      0.181      0.286      0.176      0.102
  USSR|Transport|AN-12         50          6     0.0203      0.167     0.0178    0.00989
USSR|Transport/Refuel.|IL-76/78         50        121       0.54      0.545      0.559      0.318
USSR|Surv./MPA|IL-20/38         50          6          0          0      0.088     0.0276
       USSR|AWACS|A-50         50          1          1          0      0.332      0.298
USSR|Strat.Bomber|TU-22M         50         82      0.273      0.427      0.304      0.147
USSR|Strat.Bomber/MAP|TU-95/142         50         74      0.548      0.376      0.532      0.358
          CIV AIRCRAFT         50         34      0.385      0.676     

val: Scanning C:\Users\Северин\Documents\unik\kursova\DB\labels\val.cache... 50 images, 0 backgrounds, 0 corrupt: 100%|██████████| 50/50 [00:00<?, ?it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:07<00:00,  1.99s/it]


                   all         50        756      0.255      0.203       0.26      0.163
            Helicopter         50         44     0.0773     0.0227     0.0705     0.0267
USSR|CIV/Transport|AN-124         50         33       0.42      0.241      0.308      0.181
USSR|CIV/Transport/Recon.|AN-24/26/30         50         21      0.223      0.333      0.189      0.107
  USSR|Transport|AN-12         50          6     0.0203      0.167     0.0193     0.0103
USSR|Transport/Refuel.|IL-76/78         50        121      0.521      0.504      0.547      0.308
USSR|Surv./MPA|IL-20/38         50          6          0          0     0.0591     0.0169
       USSR|AWACS|A-50         50          1          1          0      0.995      0.895
USSR|Strat.Bomber|TU-22M         50         82       0.27      0.415      0.281      0.143
USSR|Strat.Bomber/MAP|TU-95/142         50         74      0.583      0.392      0.538       0.37
          CIV AIRCRAFT         50         34      0.397      0.735     

In [1]:
test = model('..\\DB\\images\\train\\0266.png')
cv2.imshow("img", test)

NameError: name 'model' is not defined

In [ ]:
#IMAGE_PROCESSING
from ultralytics import YOLO

# Load a model
# model = YOLO('yolov8n.yaml')
model = YOLO('CustomPlane_copy.yaml')
model = YOLO('./pts/yolov8n.pt')

hyp = {
       'flipud': 0.5,
       'fliplr': 0.5,
       'rotate': 0.5,
       'mosaic': 0.3,
       'mixup':  0.05
}

# Train and use the model with 527 images
results = model.train(data='./CustomPlane_copy.yaml', epochs=500, imgsz=1000, hyp=hyp) 
results = model.val()
# results = model('../RUSSIAN_PLANAE_DB/original/0266.png')



In [ ]:
import cv2
# model = YOLO('D:/DesktopFolders/Універ/5курс/Сем_2/ООП/neuron/ultralytics-main/examples/best_laplace_contrast.pt')
model = YOLO('./pts/best_laplace_contrast.pt')
# image='D:/temp_2/0223.png'
image='../img_db/RUSSIAN_PLANAE_DB/0223.png'
img = cv2.imread(image)
class_name_dict = {
    0: 'Helicopter',
    1:'USSR|CIV/Transport|AN-124',
    2:'USSR|CIV/Transport/Recon.|AN-24/26/30',
    3:'USSR|Transport|AN-22',
    4:'USSR|Transport|AN-12',
    5:'USSR|CIV/Transport|AN-2',
    6:'USSR|Transport/Refuel.|IL-76/78',
    7:'USSR|Surv./MPA|IL-20/38',
    8:'CZECHOSLOVAKIA|Trainer/G-A|L-39',
    9:'RUSSIA|Trainer|YAK-130',
    10:'USSR|AWACS|A-50',
    11:'USSR|Bomber|TU-22',
    12:'USSR|Strat.Bomber|TU-22M',
    13:'USSR|Strat.Bomber/MAP|TU-95/142',
    14:'USSR|Strat.Bomber|TU-160',
    15:'USSR|Trainer|TU-134',
    16:'CIV AIRCRAFT',
    17:'USSR|Interceptor/G-A|MIG-31',
    18:'USSR|Fighter|MIG-29',
    19:'USSR|Mutlirole Fighter|SU-27/30/33/35',
    20:'USSR|Fighter/Bomber|SU-34',
    21:'USSR|CAS|SU-25',
    22:'USSR|Tact.Bomber|SU-24'
}
results = model(img)[0]   
for result in results.boxes.data.tolist():
            x1, y1, x2, y2, score, class_id = result
            cv2.rectangle(img, (int(x1), int(y1)), (int(x2), int(y2)), (0, 255, 0), 4)
            cv2.putText(img, class_name_dict[int(class_id)].upper(), (int(x1), int(y1 - 10)),
            cv2.FONT_HERSHEY_SIMPLEX,0.5, (0, 255, 0), 1, cv2.LINE_AA)
            cv2.imwrite('recognized.jpg',img)

In [ ]:
# colab version of train


from ultralytics import YOLO
import os

# Load a model
# model = YOLO('yolov8n.yaml')
data = project_folder + 'src/CustomPlane_copy.yaml'

# load model
model = YOLO('yolov8n.yaml')
model = YOLO('yolov8n.pt')

# Train and use the model with 527 images
results = model.train(data=data, epochs=100, imgsz=720, augment=True, batch=16)
results = model.val()
# results = model('../RUSSIAN_PLANAE_DB/original/0266.png')